language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=54

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
  - sudo apt-get update -qq
  - https://github.com/jasp-stats/jasp-desktop.git
install:
  - sudo apt-get install libqt5widgets5 libqt5webkit5-dev libqt5svg5-dev
  - sudo apt-get install libboost-dev libboost-filesystem-dev libboost-system-dev
  - sudo apt-get install libarchive-dev
  
script:
  - cd jasp-desktop
  - sudo qmake -r
  - sudo make
  - sudo make check
