language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=54

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt541 -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install libqt5webkit5-dev
  - sudo apt-get install qt54base qt54websockets qt
script:
  - source /opt/qt54/bin/qt54-env.sh
  - qmake -r
  - make
  - make check
