language: cpp

compiler:
  - gcc

sudo: required
dist: trusty

env:
  - QT_BASE=54

before_install:
  - if [ "$QT_BASE" = "54" ]; then sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "54" ]; then sudo apt-get install -qq qt54base; source /opt/qt54/bin/qt54-env.sh; fi

script:
  - qmake -r
  - make
  - make check
