    language: cpp
    
    compiler:
      - gcc
    
    sudo: required
    dist: trusty
    
    env:
      - QT_BASE=54
    
    before_install:
      - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
      - sudo apt-get update -qq
    install:
      - sudo apt-get install libqt5webkit5-dev
    script:
      - qmake -r
      - make
      - make check
